all: sudu

sudu:
	g++ -std=c++17  -o sudu main.cpp ./block/block.cpp ./command/command.cpp ./i18n/i18n.cpp ./input/input.cpp ./scene/scene.cpp
#	g++ -std=c++17 -g -o sudu main.cpp ./block/block.cpp ./command/command.cpp ./i18n/i18n.cpp ./input/input.cpp ./scene/scene.cpp

clean:
	rm -r sudu
